---

- name: install bind9
  apt:
    name: bind9
    state: present

- name: copy template
  template:
    src: ../templates/named.conf.options.j2
    dest: /tmp/named.conf.options
    owner: root
    group: root
    mode: 0644

- name: restart bind service
  systemd:
    name: bind9
    state: restarted
    daemon_reload: yes
