---
- name: Get info on Docker Swarm
  docker_swarm_info:
  ignore_errors: yes
  register: result

# - name: Inform about basic flags
#   debug:
#     msg:
#       - "{{ result }}"
#       - "Was able to talk to docker daemon: {{ result.can_talk_to_docker }}"
#       - "Docker in Swarm mode: {{ result.docker_swarm_active }}"
#       - "This is a Manager node: {{ result.docker_swarm_manager }}"

# - block:
#     - name: Get info on Docker Swarm and list of registered nodes
#       docker_swarm_info:
#         nodes: yes
#       register: result

#     - name: Get info on Docker Swarm and extended list of registered nodes
#       docker_swarm_info:
#         nodes: yes
#         verbose_output: yes
#       register: result

#     - name: Get info on Docker Swarm and filtered list of registered nodes
#       docker_swarm_info:
#         nodes: yes
#         nodes_filter:
#           name: "{{ nodes }}"
#       loop: "{{ swarm_nodes }}"
#       loop_control:
#         loop_var: nodes
#       register: result

#     - debug:
#         var: result.swarm_facts
#   when: result.docker_swarm_active 

- name: Create swarm cluster 
  docker_swarm:
    state: "{{ swarm_state }}"
    advertise_addr: eno1:2377
    force: yes
  register: output
  when: role == master

- name: Create swarm cluster 
  docker_swarm:
    state: "{{ swarm_state }}"
    advertise_addr: eno1:2377
    force: yes
  register: output
  when: role == manager

# - name: Get the swarm unlock key
#   docker_swarm_info:
#     unlock_key: yes
#   register: result

# - debug:
#     var: result.swarm_unlock_key

