---

- name: copy interfaces template
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644


- name: restart network manager
  systemd:
    name: networking
    state: restarted
    